#!/usr/bin/env bash
# Generate Nim bindings from the Rust shim using nbindgen, then apply fixups.
#
# Usage: ./tools/generate_bindings.sh
#
# Requires: nbindgen (cargo install nbindgen), sed
#
# The raw nbindgen output needs several fixups because nbindgen doesn't fully
# understand the Nim idioms we want:
#   1. *const c_char maps to `pointer` — we want `cstring`
#   2. No dynlib pragma is emitted — we need it for runtime linking
#   3. GpuiElement is emitted as a struct — we want an opaque pointer
#   4. NodeId type is emitted but not needed on the Nim side

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHIM_CRATE="$REPO_ROOT/rust/gpui-nim-shim"
RAW_OUTPUT="$REPO_ROOT/src/isonim_gpui/bindings_nbindgen_raw.nim"
FINAL_OUTPUT="$REPO_ROOT/src/isonim_gpui/bindings_generated.nim"

# Step 1: Run nbindgen
echo "Running nbindgen on $SHIM_CRATE ..."
nbindgen --crate gpui-nim-shim "$SHIM_CRATE" -o "$RAW_OUTPUT" 2>&1 | grep -v '^$' || true

echo "Raw nbindgen output saved to $RAW_OUTPUT"

# Step 2: Extract function names from the raw output for validation
RAW_FUNCS=$(grep -oP 'proc \K\w+(?=\*)' "$RAW_OUTPUT" | sort)
echo "Found $(echo "$RAW_FUNCS" | wc -l) function bindings in nbindgen output"

# Step 3: Extract function names from Rust source for cross-check
RUST_FUNCS=$(grep -oP 'pub extern "C" fn \K\w+' "$SHIM_CRATE/src/lib.rs" | sort)
RUST_COUNT=$(echo "$RUST_FUNCS" | wc -l)
echo "Found $RUST_COUNT extern \"C\" functions in Rust source"

# Step 4: Check for missing bindings
MISSING=$(comm -23 <(echo "$RUST_FUNCS") <(echo "$RAW_FUNCS"))
if [ -n "$MISSING" ]; then
    echo "WARNING: The following Rust exports are missing from nbindgen output:"
    echo "$MISSING"
fi

EXTRA=$(comm -13 <(echo "$RUST_FUNCS") <(echo "$RAW_FUNCS"))
if [ -n "$EXTRA" ]; then
    echo "NOTE: Extra bindings in nbindgen output (not extern C):"
    echo "$EXTRA"
fi

# Step 5: Generate the final bindings file with fixups
cat > "$FINAL_OUTPUT" << 'HEADER'
## Auto-generated by nbindgen from rust/gpui-nim-shim/src/lib.rs
## DO NOT EDIT — regenerate with: just generate-bindings
##
## Note: This file is the raw nbindgen output with manual fixups applied by
## tools/generate_bindings.sh:
##   - `pointer` parameters for C strings are replaced with `cstring`
##   - `dynlib` pragma is added for runtime linking
##   - GpuiElement is treated as an opaque pointer (not a struct with fields)
##   - Unnecessary NodeId type is removed

type
  GpuiElementObj* {.importc: "GpuiElement", header: "".} = object
  GpuiElement* = ptr GpuiElementObj
    ## Opaque handle to a GPUI element managed by the Rust shim.

const shimLib = "libgpui_nim_shim.so" # TODO: platform-specific (.dylib on macOS)

HEADER

# Extract types (EventCallback, RootBuilderCallback, etc.) from raw output and fix them
echo '## C function pointer types for callbacks from Nim.' >> "$FINAL_OUTPUT"
echo 'type EventCallback* = proc() {.cdecl.}' >> "$FINAL_OUTPUT"
echo 'type RootBuilderCallback* = proc(root: GpuiElement) {.cdecl.}' >> "$FINAL_OUTPUT"
echo 'type ResizeCallback* = proc(width: cdouble; height: cdouble) {.cdecl.}' >> "$FINAL_OUTPUT"
echo 'type FocusCallback* = proc(focused: uint8) {.cdecl.}' >> "$FINAL_OUTPUT"
echo 'type CloseCallback* = proc(): uint8 {.cdecl.}' >> "$FINAL_OUTPUT"
echo '' >> "$FINAL_OUTPUT"
echo '{.push cdecl, dynlib: shimLib.}' >> "$FINAL_OUTPUT"
echo '' >> "$FINAL_OUTPUT"

# Extract proc declarations from raw output and apply fixups
# - Replace `pointer` with `cstring` for string parameters
# - Replace `ptr GpuiElement` with `GpuiElement` (since our GpuiElement is already a ptr)
# - Replace `: void` with nothing (Nim style)
# - Add dynlib pragma
grep '^proc \|^                ' "$RAW_OUTPUT" | \
    sed 's/: pointer/: cstring/g' | \
    sed 's/ptr GpuiElement/GpuiElement/g' | \
    sed 's/: void {/ {/g' | \
    sed 's/): void {/) {/g' | \
    sed 's/(): void/() /g' | \
    sed 's/): GpuiElement/): GpuiElement\n /g' >> "$FINAL_OUTPUT"

echo '' >> "$FINAL_OUTPUT"
echo '{.pop.}' >> "$FINAL_OUTPUT"

echo ""
echo "Generated $FINAL_OUTPUT"
echo "Done."
